// Phase 3 - MITM Re-Attempt Against the New Protocol (spec 4.2)
//
// Run on the Mallory VM, exactly as in Phase 2 -- but this time Mallory
// cannot get past the very first step. Mallory does not have the CA's
// PRIVATE key (ca.key), so it cannot produce a certificate that will pass
// signature_chains_to_ca() on the victim's side. This program presents
// mallory.crt (a SELF-signed certificate, generated by setup_ca.sh,
// claiming the same CN as the real server to be maximally deceptive) and
// simply logs whatever the victim's client does next -- which, if the
// victim is running the Phase 3 client correctly, will be an immediate
// disconnect with NO further data sent (no nonce, no DH value, nothing).
//
// Note this program never even attempts to relay to the real server --
// there's no point building out that plumbing, because the attack is
// defeated at the very first step, before any of that would matter. This
// is the direct contrast against Phase 2, where the same "point the victim
// at Mallory" setup fully succeeded.
//
// Usage: ./mallory_proxy_phase3 <listen_port>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <unistd.h>

#include <cstring>
#include <ctime>
#include <iostream>
#include <string>

#include "../common/cert_utils.h"
#include "../common/framing.h"

static const char *MALLORY_CERT_PATH = "mallory.crt";
static const char *MALLORY_KEY_PATH = "mallory.key";

static std::string timestamp() {
    std::time_t t = std::time(nullptr);
    char buf[32];
    std::strftime(buf, sizeof(buf), "%H:%M:%S", std::localtime(&t));
    return std::string(buf);
}
static void log(const std::string &msg) {
    std::cout << "[" << timestamp() << "] " << msg << std::endl;
}

int main(int argc, char *argv[]) {
    int port = argc > 1 ? std::atoi(argv[1]) : 5000;

    cert::X509Ptr mallory_cert;
    cert::PKeyPtr mallory_key;
    try {
        mallory_cert = cert::load_cert_from_file(MALLORY_CERT_PATH);
        mallory_key = cert::load_private_key_from_file(MALLORY_KEY_PATH);
    } catch (const std::exception &e) {
        std::cerr << "Failed to load " << MALLORY_CERT_PATH << "/" << MALLORY_KEY_PATH
                  << ": " << e.what() << "\n";
        std::cerr << "Run setup_ca.sh (on the Server VM) and copy mallory.crt + "
                     "mallory.key here first.\n";
        return 1;
    }
    log("Loaded mallory.crt -- a SELF-signed certificate, NOT signed by the real "
        "CA. This is the only certificate Mallory can produce, since it does not "
        "have ca.key.");

    int listen_fd = socket(AF_INET, SOCK_STREAM, 0);
    int opt = 1;
    setsockopt(listen_fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));
    sockaddr_in addr{};
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = INADDR_ANY;
    addr.sin_port = htons(port);
    if (bind(listen_fd, (sockaddr *)&addr, sizeof(addr)) < 0) {
        perror("bind");
        return 1;
    }
    listen(listen_fd, 4);
    log("Mallory (Phase 3 attempt) listening on port " + std::to_string(port) +
        ". Point the victim client at THIS machine instead of the real server.");

    while (true) {
        sockaddr_in victim_addr{};
        socklen_t victim_len = sizeof(victim_addr);
        int victim_fd = accept(listen_fd, (sockaddr *)&victim_addr, &victim_len);
        if (victim_fd < 0) continue;
        char ip[INET_ADDRSTRLEN];
        inet_ntop(AF_INET, &victim_addr.sin_addr, ip, sizeof(ip));
        log("Victim connected from " + std::string(ip));

        LineReader reader{victim_fd, ""};

        if (!send_line(victim_fd, "CERT " + cert::cert_to_wire(mallory_cert))) {
            log("Failed to send certificate to victim");
            close(victim_fd);
            continue;
        }
        log("Sent our self-signed certificate to the victim. Waiting to see if "
            "they proceed...");

        std::string nonce_line;
        if (!reader.recv_line(nonce_line)) {
            log("*** VICTIM DISCONNECTED WITHOUT SENDING ANYTHING FURTHER. ***");
            log("This means their client's certificate validation FAILED and it "
                "aborted immediately -- exactly the spec 4.1 requirement (no "
                "nonce, no DH value, no data leaked). Contrast this with Phase 2, "
                "where the same setup fully succeeded.");
        } else {
            // Only reachable if the victim's client is NOT correctly validating
            // certificates -- i.e. a bug on the victim side, not a success for
            // Mallory (Mallory still can't produce a valid PoP signature that
            // would pass verify_challenge() against its self-signed cert's key,
            // since the victim's expected CA-signed identity check would have
            // already failed first in a correct implementation).
            log("Unexpected: victim sent '" + nonce_line +
                "' -- their certificate validation did not reject our fake cert. "
                "Check the client's validate_certificate() logic.");
        }

        close(victim_fd);
        log("Session ended, ready for next attempt.");
    }
    return 0;
}
